function [ f ] = Extract_features_GLCMAO(Img,d,levelsNum)
% Computes GLCM Features


    glcm = graycomatrix(Img, 'NumLevels', levelsNum, 'GrayLimits', [0 255], 'Offset', d.*[0 1]);
    ft=GLCM_Features1(glcm);
    f1=[ ft.autoc ft.contr ft.corrm ft.corrp ft.cprom  ft.cshad ft.dissi ...
        ft.energ ft.entro ft.homom ft.homop ft.maxpr ft.sosvh ft.savgh ... 
        ft.svarh ft.senth ft.dvarh ft.denth ft.inf1h ft.inf2h ft.indnc...
        ft.idmnc];
    glcm = graycomatrix(Img, 'NumLevels', levelsNum, 'GrayLimits', [0 255], 'Offset', d.*[-1 1]);
     ft=GLCM_Features1(glcm);
    f2=[ ft.autoc ft.contr ft.corrm ft.corrp ft.cprom  ft.cshad ft.dissi ...
        ft.energ ft.entro ft.homom ft.homop ft.maxpr ft.sosvh ft.savgh ... 
        ft.svarh ft.senth ft.dvarh ft.denth ft.inf1h ft.inf2h ft.indnc...
        ft.idmnc];
    glcm = graycomatrix(Img, 'NumLevels', levelsNum, 'GrayLimits', [0 255], 'Offset', d.*[-1 0]);
     ft=GLCM_Features1(glcm);
    f3=[ ft.autoc ft.contr ft.corrm ft.corrp ft.cprom  ft.cshad ft.dissi ...
        ft.energ ft.entro ft.homom ft.homop ft.maxpr ft.sosvh ft.savgh ... 
        ft.svarh ft.senth ft.dvarh ft.denth ft.inf1h ft.inf2h ft.indnc...
        ft.idmnc];
    glcm = graycomatrix(Img, 'NumLevels', levelsNum, 'GrayLimits', [0 255], 'Offset', d.*[-1 -1]);
     ft=GLCM_Features1(glcm);
    f4=[ ft.autoc ft.contr ft.corrm ft.corrp ft.cprom  ft.cshad ft.dissi ...
        ft.energ ft.entro ft.homom ft.homop ft.maxpr ft.sosvh ft.savgh ... 
        ft.svarh ft.senth ft.dvarh ft.denth ft.inf1h ft.inf2h ft.indnc...
        ft.idmnc];
    
    f=mean(f1+f2+f3+f4,1);
    
    
   

end

